name = "shiny-art-b402" # todo
main = "./dist/main.js"
compatibility_date = "2022-10-10"

[vars]
EMAIL_TIMEOUT = 3600

[[kv_namespaces]]
binding = "MISSO_EMAILS"
id = "a0f22d03d73749aab676c00a96b07b34"


[observability]
enabled = true
head_sampling_rate = 1